//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I2CDownload
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I2CDownload.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AFETrim (Hex) 的本地化字符串。
        /// </summary>
        internal static string AFETrim {
            get {
                return ResourceManager.GetString("AFETrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APPCode 的本地化字符串。
        /// </summary>
        internal static string APPCode {
            get {
                return ResourceManager.GetString("APPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Bin file don&apos;t exist. 的本地化字符串。
        /// </summary>
        internal static string BinFileNotExist {
            get {
                return ResourceManager.GetString("BinFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BinName 的本地化字符串。
        /// </summary>
        internal static string BinName {
            get {
                return ResourceManager.GetString("BinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BinRev 的本地化字符串。
        /// </summary>
        internal static string BinRev {
            get {
                return ResourceManager.GetString("BinRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CDBTrigMode (Hex) 的本地化字符串。
        /// </summary>
        internal static string CDBCMDTrigMode {
            get {
                return ResourceManager.GetString("CDBCMDTrigMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataLen Len(Hex) 的本地化字符串。
        /// </summary>
        internal static string CDBDataLen {
            get {
                return ResourceManager.GetString("CDBDataLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CDBDataModel (Hex) 的本地化字符串。
        /// </summary>
        internal static string CDBDataModel {
            get {
                return ResourceManager.GetString("CDBDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CDBHeader Len(Hex) 的本地化字符串。
        /// </summary>
        internal static string CDBHeaderLen {
            get {
                return ResourceManager.GetString("CDBHeaderLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CDB PW(Hex) 的本地化字符串。
        /// </summary>
        internal static string CDBPW {
            get {
                return ResourceManager.GetString("CDBPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CDBType (Hex) 的本地化字符串。
        /// </summary>
        internal static string CDBType {
            get {
                return ResourceManager.GetString("CDBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CDRParams (Hex) 的本地化字符串。
        /// </summary>
        internal static string CDRParams {
            get {
                return ResourceManager.GetString("CDRParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Connect before Downloading 的本地化字符串。
        /// </summary>
        internal static string ConnectbeforeDownloading {
            get {
                return ResourceManager.GetString("ConnectbeforeDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Connect before Verifying 的本地化字符串。
        /// </summary>
        internal static string ConnectbeforeVerifying {
            get {
                return ResourceManager.GetString("ConnectbeforeVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected 的本地化字符串。
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Fail 的本地化字符串。
        /// </summary>
        internal static string ConnectFail {
            get {
                return ResourceManager.GetString("ConnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect didn&apos;t Complete 的本地化字符串。
        /// </summary>
        internal static string ConnectnotComplete {
            get {
                return ResourceManager.GetString("ConnectnotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Successful 的本地化字符串。
        /// </summary>
        internal static string ConnectSuccessful {
            get {
                return ResourceManager.GetString("ConnectSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Time 的本地化字符串。
        /// </summary>
        internal static string CurrentTime {
            get {
                return ResourceManager.GetString("CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Connected 的本地化字符串。
        /// </summary>
        internal static string DeviceConnected {
            get {
                return ResourceManager.GetString("DeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Device Connected 的本地化字符串。
        /// </summary>
        internal static string DeviceDisconnected {
            get {
                return ResourceManager.GetString("DeviceDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect Fail 的本地化字符串。
        /// </summary>
        internal static string DisconnectFail {
            get {
                return ResourceManager.GetString("DisconnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect didn&apos;t complete 的本地化字符串。
        /// </summary>
        internal static string Disconnectnotcomplete {
            get {
                return ResourceManager.GetString("Disconnectnotcomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect Successful 的本地化字符串。
        /// </summary>
        internal static string DisconnectSuccessful {
            get {
                return ResourceManager.GetString("DisconnectSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading 的本地化字符串。
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed Downloading 的本地化字符串。
        /// </summary>
        internal static string FailedDownloading {
            get {
                return ResourceManager.GetString("FailedDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed Downloading File 的本地化字符串。
        /// </summary>
        internal static string FailedDownloadingFile {
            get {
                return ResourceManager.GetString("FailedDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please insert module. 的本地化字符串。
        /// </summary>
        internal static string InsertModule {
            get {
                return ResourceManager.GetString("InsertModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MediaInterface (Hex) 的本地化字符串。
        /// </summary>
        internal static string MediaInterface {
            get {
                return ResourceManager.GetString("MediaInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModuleForm 的本地化字符串。
        /// </summary>
        internal static string ModuleForm {
            get {
                return ResourceManager.GetString("ModuleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModuleRev 的本地化字符串。
        /// </summary>
        internal static string ModuleRev {
            get {
                return ResourceManager.GetString("ModuleRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Device to be Connected 的本地化字符串。
        /// </summary>
        internal static string NoDeviceConnected {
            get {
                return ResourceManager.GetString("NoDeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No file was selected 的本地化字符串。
        /// </summary>
        internal static string NofileSelected {
            get {
                return ResourceManager.GetString("NofileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Plug USB Device 的本地化字符串。
        /// </summary>
        internal static string PlugUSBDevice {
            get {
                return ResourceManager.GetString("PlugUSBDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program restart required for settings to take affect! 的本地化字符串。
        /// </summary>
        internal static string ProgramRestartSettings {
            get {
                return ResourceManager.GetString("ProgramRestartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please pullout module. 的本地化字符串。
        /// </summary>
        internal static string PulloutModule {
            get {
                return ResourceManager.GetString("PulloutModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PWAddr (Hex) 的本地化字符串。
        /// </summary>
        internal static string PWAddr {
            get {
                return ResourceManager.GetString("PWAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PWDev Addr(Hex) 的本地化字符串。
        /// </summary>
        internal static string PWDevAddr {
            get {
                return ResourceManager.GetString("PWDevAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PWPage (Hex) 的本地化字符串。
        /// </summary>
        internal static string PWPage {
            get {
                return ResourceManager.GetString("PWPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RevLen (Hex) 的本地化字符串。
        /// </summary>
        internal static string RevLen {
            get {
                return ResourceManager.GetString("RevLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RevPage (Hex) 的本地化字符串。
        /// </summary>
        internal static string RevPage {
            get {
                return ResourceManager.GetString("RevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RevReg Addr(Hex) 的本地化字符串。
        /// </summary>
        internal static string RevRegAddr {
            get {
                return ResourceManager.GetString("RevRegAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SCDREN (Hex) 的本地化字符串。
        /// </summary>
        internal static string SCDREN {
            get {
                return ResourceManager.GetString("SCDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SCDRMulSel (Hex) 的本地化字符串。
        /// </summary>
        internal static string SCDRMulSel {
            get {
                return ResourceManager.GetString("SCDRMulSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        internal static string SimplifiedChinese {
            get {
                return ResourceManager.GetString("SimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify a Bin file to Download 的本地化字符串。
        /// </summary>
        internal static string SpecifyBinfileDownload {
            get {
                return ResourceManager.GetString("SpecifyBinfileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify a Bin file to verify 的本地化字符串。
        /// </summary>
        internal static string SpecifyBinfileVerify {
            get {
                return ResourceManager.GetString("SpecifyBinfileVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded Downloading 的本地化字符串。
        /// </summary>
        internal static string SucceededDownloading {
            get {
                return ResourceManager.GetString("SucceededDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded Downloading Bin File.  Checksum:0x 的本地化字符串。
        /// </summary>
        internal static string SucceededDownloadingBinFile {
            get {
                return ResourceManager.GetString("SucceededDownloadingBinFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testboard is connected 的本地化字符串。
        /// </summary>
        internal static string TestboardConnected {
            get {
                return ResourceManager.GetString("TestboardConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testboard is disconnected 的本地化字符串。
        /// </summary>
        internal static string TestboardDisconnected {
            get {
                return ResourceManager.GetString("TestboardDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time: 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification failed. 的本地化字符串。
        /// </summary>
        internal static string Verificationfailed {
            get {
                return ResourceManager.GetString("Verificationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification passed 的本地化字符串。
        /// </summary>
        internal static string Verificationpassed {
            get {
                return ResourceManager.GetString("Verificationpassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
